#!/usr/bin/env bash
set -e
set -o xtrace

export GIT_COMMIT="v_$(git rev-parse --short HEAD)"
export DOCKER_REPO=healthsamurai/ci3

lein uberjar

docker build -t $DOCKER_REPO:$GIT_COMMIT .
docker tag $DOCKER_REPO:$GIT_COMMIT $DOCKER_REPO:latest
gcloud docker -- push $DOCKER_REPO:$GIT_COMMIT
gcloud docker -- push $DOCKER_REPO:latest
## helm upgrade -f secret/values.yaml--set image.tag=$GIT_COMMIT,image.repository=$DOCKER_REPO -i ci ci3
