#!/usr/bin/env bash
set -e
set -o xtrace

#export DOCKER_KEY="$(kubectl get secrets docker-registry -o json | jq -r '.data.key' | base64 --decode)"
export GIT_COMMIT="v_$(git rev-parse --short HEAD)"

lein uberjar

#docker login -u _json_key -p "$DOCKER_KEY" https://eu.gcr.io
docker build -t eu.gcr.io/vivid-kite-171620/ci3:$GIT_COMMIT .
gcloud docker -- push eu.gcr.io/vivid-kite-171620/ci3:$GIT_COMMIT
helm upgrade --set image.tag=$GIT_COMMIT,image.repository=eu.gcr.io/vivid-kite-171620/ci3 -i ci3 ci3
