#!/bin/bash

set -e

echo 'starting'

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
  echo "export key"
  export KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
fi

if [ -n "$KUBERNETES_SERVICE_HOST" ]; then
  export KUBE_URL="https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT"
fi

case $1 in
  "agent" )
    java -cp /var/ci3.jar clojure.main -m ci3.agent;;
  "server" )
    java -cp /var/ci3.jar clojure.main -m ci3.server;;
  *)
    echo "Please choose subcomands: agent, server";;
esac
