---
apiVersion: v1
kind: Pod
metadata:
  name: zero-ci-agent-4
  labels:
    system: dev
spec:
  restartPolicy: Never
  containers:
  - name: agent
    image: aidbox/ci3:0.0.1
    imagePullPolicy: Always
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    env:
    - name: BUILD_ID
      value: build-2
    - name: DOCKER_KEY
      valueFrom:
        secretKeyRef:
          name: docker-registry
          key: key
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
