#!/usr/bin/env bash
set -e
# set -o xtrace

export APISERVER=$(kubectl config view | grep server | cut -f 2- -d ":" | tr -d " ")
export TOKEN=$(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t')
export DOCKER_KEY="$(kubectl get secrets docker-registry -o json | jq -r '.data.key' | base64 --decode)"
export SERVICE_ACCOUNT="$(kubectl get secrets docker-registry -o json | jq -r '.data.key' | base64 --decode)"
export CACHE_BUCKET="ci3-cache"

lein uberjar
java -cp target/ci3.jar clojure.main -m ci3.core agent