apiVersion: v1
data:
  DOCKER_HUB: ~
  DOCKER_PASSWORD: ~
  DOCKER_USER: ~
  GITHUB_TOKEN: ~
  TELEGRAM_CHATID: ~
  TELEGRAM_TOKEN: ~
kind: Secret
metadata:
  annotations:
  name: ci3
  namespace: default
type: Opaque
