apiVersion: v1
data:
  # DOCKER_HUB: ~
  # DOCKER_PASSWORD: ~
  # DOCKER_USER: ~


  #
  # All values here are exposed to ci3 server and agents via env variables
  # with CI3_SECRET_ prefix
  # $CI3_SECRET_GITHUB_TOKEN often used for checkouting submodules,
  # example can be found in ../repo-configs/ci3.yaml
  #
  # echo -n "YOUR-VALUE" | base64 -w 0
  #
  GITHUB_TOKEN: ~

  #
  # YOUR:TOKEN is a value you've got from @BotFather
  # https://web.telegram.org/#/im?p=@BotFather
  #
  # to get CHATID use following url:
  # https://api.telegram.org/botYOUR:TOKEN/getUpdates
  #
  # Encode to base64 both values and put them to fields
  #
  # echo -n "YOUR-VALUE" | base64 -w 0
  #
  TELEGRAM_CHATID: - PUT-YOUR-CHATID-HERE -
  TELEGRAM_TOKEN: - PUT-YOUR-TOKEN-HERE -
kind: Secret
metadata:
  annotations:
  name: ci3
  namespace: default
type: Opaque
