apiVersion: v1
data:

  #
  # 1. Go to GCE Console > IAM & Admin > Service accounts
  # 2. Create new service account ci3-storage with role Storage > Storage Admin
  # 3. Select Furnish a new private key and create account
  # 4. Rename obtained key to ci3-storage-key.json
  # 5. Encode key and put it to key field
  # cat ci3-storage-key.json | base64 -w 0
  #
  account:

  #
  # 1. Update storage-secret-boto file with proper default_project_id
  # 2. Put base64 encoded value of file to boto field
  # cat storage-secret-boto | base64 -w 0
  #
  boto:
kind: Secret
metadata:
  annotations:
  name: storage
  namespace: default
type: Opaque
