apiVersion: v1
data:
  account: ~
  boto: W0NyZWRlbnRpYWxzXQpnc19zZXJ2aWNlX2tleV9maWxlID0gL2dzdXRpbC9hY2NvdW50Lmpzb24KW0JvdG9dCmh0dHBzX3ZhbGlkYXRlX2NlcnRpZmljYXRlcyA9IFRydWUKW0dvb2dsZUNvbXB1dGVdCltHU1V0aWxdCmNvbnRlbnRfbGFuZ3VhZ2UgPSBlbgpkZWZhdWx0X2FwaV92ZXJzaW9uID0gMgpkZWZhdWx0X3Byb2plY3RfaWQgPSBtZW50cmljcwpbT0F1dGgyXQo=
kind: Secret
metadata:
  annotations:
  name: storage
  namespace: default
type: Opaque
