apiVersion: "ci3.io/v1"
kind: Repository
metadata:
  name: ci3
#
# Change url and fullName according to your project requirements
#
url: https://github.com/HealthSamurai/ci3
type: github
fullName: HealthSamurai/ci3
oauthConsumer:
  token:
    valueFrom:
      secretKeyRef:
        name: github
        key: token

# 1. Change github.yaml according your needs
# 2. kubectl apply -f repo.yaml github.yaml
# 3. Copy ci3.yaml to your project and modify it
# 4. Setup a webhook if you didn't do it yet
